meta:
  title: ""
  description: ""
  facebook_image: ""  # /img/facebook.png
  twitter_image: ""  # /img/twitter.png
  image: ""  # /img/share.png
  twitter_handle: ""  # @minimill_co
  domain: ""  # minimill.co
  url: ""  # https://minimill.co
  google_analytics_id: "" # UA-66637918-1
  theme_color: "" # #FFFFFF

name: ""
markdown: redcarpt
highlighter: pygments
permalink: "/:categories/:title/"

gems:
  - jekyll-redirect-from

exclude:
  - node_modules
  - Gulpfile.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - redirects.json
  - README.md
  - LICENSE.md
